"""
Django settings for HPC project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from django.urls import reverse_lazy
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*(3pnp)ww7)yth1+fs8_0na(!%!&%p4#57@8)+*=1768)we7l#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['hipocampo.dimpera.com', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'crispy_forms',
    'crispy_bootstrap5',
    'USERDATA.apps.UserdataConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HPC.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HPC.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
      'default':{
     'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
     'default1': {
       'ENGINE': 'mssql',
        'NAME': 'CSKY-HIPOCAMPO',
        'USER': 'usr-csky-hipocampo-web',
        'PASSWORD': 'pXyF6D5VH7TRqkzJ',
        'HOST': 's3.cloud.csky.com.ar',
        'PORT': '15016',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            "setencoding": [{"encoding": "utf-8"}],
        }
        },

    'default2': {
       'ENGINE': 'mssql',
        'NAME': 'Hipocampo',
        'USER': '',
        'PASSWORD': '',
        'HOST': 'DESKTOP-MTJLAID\SQLEXPRESS',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            "setencoding": [{"encoding": "utf-8"}],
        },
        }
       
    

}

''' NAME: CSKY-HIPOCAMPO
SERVER: s3.cloud.csky.com.ar
PORT: 15016
USER: usr-csky-hipocampo-web
PASS: pXyF6D5VH7TRqkzJ
VERSION: 2019 

    'hipocampo': {
        'ENGINE': 'mssql',
        'NAME': 'CSKY-HIPOCAMPO',
        'USER': 'usr-csky-hipocampo-web',
        'PASSWORD': 'pXyF6D5VH7TRqkzJ',
        'HOST': 's3.cloud.csky.com.ar',
        'PORT': '15016',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
         'unicode_results': True,
            'extra_params': 'ClientCharset=utf8'
    } 

    'default':{
     'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }

'''

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_ROOT = os.getenv('DJANGO_STATIC_ROOT', '/home/debian/hipocampo/HPC/static')
STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#varible de redireccion
LOGIN_REDIRECT_URL = reverse_lazy('home')

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')